#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define MAJOR_VERSION_INT      1
#define SUB_VERSION_INT        0
#define RELEASE_NUMBER_INT     0
#define BUILD_NUMBER_INT       123
#define FULL_VERSION_STR       "1.0.0.123"
#define stringOriginalFilename "Saturator.vst3"
#define stringFileDescription  "Saturator VST3 Plugin"
#define stringCompanyName      "dev-vlab.ru"
#define stringLegalCopyright   "Copyright (c) 2024 dev-vlab.ru"
#define stringLegalTrademarks  "VST is a trademark of Steinberg Media Technologies GmbH"
