#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"Saturator.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"Saturator VST3 (64Bit)"
#else
#define stringFileDescription	"Saturator VST3"
#endif
#define stringCompanyName		"dev-vlab.ru\0"
#define stringLegalCopyright	"Copyright(c) 2024 dev-vlab.ru."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
